#!/bin/bash

# Solve a Project Euler question with a given language.
#
# Expects files to be in a directory the same name of the language,
# named with the convention e###.whtvr (ex: "/haskell/e001.hs")
#
# Usage: sh solve.sh [language] [problem number]

if [ $# = 2 ]; then {

    if [ $1 = "c++" ]; then

        printf "\nRunning the C++ solution for problem #%03d:\n\n" $2

        g++ -std=c++11 `printf "./c++/e%03d.cpp" $2` -o e; wait

        ./e; wait; echo;

        rm e

    elif [ $1 = "python" ]; then

        printf "\nRunning the Python solution for problem #%03d:\n\n" $2

        python `printf "./python/e%03d.py" $2`; wait; echo;

    elif [ $1 = "haskell" ]; then

        printf "\nRunning the Haskell solution for problem #%03d:\n\n" $2

        ghc `printf "./haskell/e%03d.hs" $2` -o e; wait

        echo; ./e; wait; echo

        rm e
        rm `printf "haskell/e%03d.hi" $2`
        rm `printf "haskell/e%03d.o" $2`

    else
        echo "that ain't a thing!"
    fi

} else
    echo "that ain't enough!"
fi

